---
galaxy_info:
  role_name: baseline
  author: Gavriel Vaknin
  description: Minimal cross-distribution baseline configuration.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - baseline
    - configuration

dependencies: []
