#!/usr/bin/env bash
#
# geninventory.sh — generate an Ansible inventory from running libvirt VMs.
#
# Usage: ./geninventory.sh [output_path]
#
# Queries libvirt for every running domain, resolves its current IPv4 address,
# and writes a YAML inventory. Run after creating or restarting VMs so the
# inventory always reflects reality rather than a remembered address.
#
# This mirrors the dynamic-inventory pattern used against cloud providers,
# where instance addresses are never stable and are always looked up at runtime.

set -euo pipefail

DEFAULT_OUTPUT="${HOME}/learn/github/projects/devops-roadmap/projects/00-configuration-baseline/ansible/inventory.yml"
OUTPUT="${1:-$DEFAULT_OUTPUT}"
VM_USER="$(whoami)"

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

command -v virsh >/dev/null 2>&1 || die "'virsh' not found."

# Collect running domains
mapfile -t domains < <(virsh list --name --state-running | sed '/^$/d')

[[ ${#domains[@]} -gt 0 ]] || die "No running VMs found. Start some first (scripts/newvm.sh)."

info "Found ${#domains[@]} running VM(s)"

tmp="$(mktemp)"
{
    echo "---"
    echo "# Generated by scripts/geninventory.sh on $(date -Iseconds)"
    echo "# Do not edit by hand — regenerate instead."
    echo "all:"
    echo "  children:"
    echo "    test:"
    echo "      hosts:"
} > "$tmp"

found=0
for domain in "${domains[@]}"; do
    ip=""
    # Retry briefly: a freshly booted VM may not have a lease yet
    for _ in {1..10}; do
        ip="$(virsh domifaddr "$domain" 2>/dev/null | awk '/ipv4/ {print $4}' | cut -d/ -f1 | head -n1)"
        [[ -n "$ip" ]] && break
        sleep 2
    done

    if [[ -z "$ip" ]]; then
        info "WARNING: no IPv4 address for '${domain}' — skipping"
        continue
    fi

    info "  ${domain} -> ${ip}"
    printf '        %s:\n          ansible_host: %s\n' "$domain" "$ip" >> "$tmp"
    found=$((found + 1))
done

[[ $found -gt 0 ]] || die "No VMs had resolvable IPv4 addresses."

{
    echo "      vars:"
    echo "        ansible_user: ${VM_USER}"
} >> "$tmp"

mkdir -p "$(dirname "$OUTPUT")"
mv "$tmp" "$OUTPUT"

info "Wrote inventory with ${found} host(s) to:"
echo "    ${OUTPUT}"
